### ISSUE TITLE
Responsive menu not working when collapsed

### ISSUE THREAD

**Issue by pierre-dessaignes** [jdanyow/aurelia-breeze-sample#1]
Hello there,

Great stuff aurelia + Breeze :)

The responsive menu is not working when collapsed:
![image](https://cloud.githubusercontent.com/assets/6525202/6110614/2a595ada-b083-11e4-8df6-027da856664e.png)

I found a fix for it. Not quiet sure if it make sense (I am no expert) ... but it is working ...

in <b>index.html</b> replace the 
```HTML
<head> ... </head>
```
element by this:
```HTML
  <head>
    <link rel="stylesheet" type="text/css" href="jspm_packages/github/twbs/bootstrap@3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="jspm_packages/github/twbs/bootstrap@3.3.2/css/bootstrap-theme.min.css">
    <script src="jspm_packages/github/components/jquery@2.1.3/jquery.min.js"></script>
    <script src="jspm_packages/github/twbs/bootstrap@3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="jspm_packages/npm/font-awesome@4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="styles/styles.css">
  </head>
```
Keep up the good work !

Pierre

**Comment by jdanyow** [comment]
Thanks for digging into this- will take a look.

**Comment by jdanyow** [comment]
closing- this repo is no longer maintained, use https://github.com/jdanyow/todo-aurelia-breeze instead.  Favoring the other sample because it has a real breeze back-end vs this one, that uses the github api
