### ISSUE TITLE
Please explain data-form.js

### ISSUE THREAD

**Issue by kristianmandrup** [jdanyow/aurelia-breeze-sample#4]
The app is pretty self explanatory, except I have some difficulty really understanding this part in `data-form.js`

```
static metadata(){ return Behavior.withProperty('entity', 'entityChanged'); } //, Behavior.withProperty('submit')]; }

  entityChanged() {
    if (this.entity) {
      this.dataProperties = this.entity.entityType.getProperties().filter(p => p.isDataProperty);
      //this.dataProperties.foreach(p => p.test = 'form-control');
    } else {
      this.dataProperties = [];
    }
  }
```

Could you explain this part with some comments or sth? Thanks.

**Comment by jdanyow** [comment]
thanks for the feedback- I'll try to get to those items in the next couple of days.

here's what's going on with the `data-form` custom element:


[repo.html](https://github.com/jdanyow/aurelia-breeze-sample/blob/master/src/repos/repo.html) is simple view that uses the `data-form` custom element.  The custom element exposes an `entity` property that repo.html has bound the view model's `repo` property to:

``` markup
<template>
  <import from='../data-form'></import>
    
  <h1>${repo.name}</h1>

  <data-form entity.bind="repo" submit.bind="submit" /> 
</template>
```

In Aurelia you identify a custom element's properties using metadata.  The metadata in [data-form.js](https://github.com/jdanyow/aurelia-breeze-sample/blob/master/src/data-form.js) identifies one property, `entity`.  It also tells the framework that when the element's `entity` property changes the `entityChanged` method should be called:

``` javascript
import {Behavior} from 'aurelia-framework';

export class DataForm {
  static metadata(){ return Behavior.withProperty('entity', 'entityChanged'); } //, Behavior.withProperty('submit')]; }

  constructor() {
    this.dataProperties = [];
  }

  entityChanged() {
    if (this.entity) {
      this.dataProperties = this.entity.entityType.getProperties().filter(p => p.isDataProperty);
      //this.dataProperties.foreach(p => p.test = 'form-control');
    } else {
      this.dataProperties = [];
    }
  }
}
```

The `entityChanged` method reacts to the entity changing by reflecting on the entity's properties and grabbing the properties that should be displayed on the data form.  (The entity is  a breeze entity so we can access it's type and data properties via it's `entityType` property.  This is not Aurelia specific)

The custom element's view is driven by this subset of properties: https://github.com/jdanyow/aurelia-breeze-sample/blob/master/src/data-form.html#L3
